### ISSUE TITLE
[Feature Tracking] 5.4 Support

### ISSUE THREAD

**Issue by UE4SS** [UE4SS-RE/RE-UE4SS#502]
This issue will be used to track where we are when it comes to supporting UE 5.4.

Items that must be addressed:
- [x] Removal of `UDynamicClass` causing an infinite search of `GUObjectArray` due to this being one of our required objects to exist during init.
      Need to remove `UDynamicClass` from being a requirement in 5.4+.
- [x] `FActorInstanceHandle::Actor` was renamed to `ReferenceObject`, `LineTraceMod` needs updating.
- [x] Add support for `UGameplayStatics::BeginDeferredActorSpawnFromClass` (UE 5.2+).
     ~~Fix BPModLoaderMod, see https://github.com/UE4SS-RE/RE-UE4SS/issues/502#issuecomment-2111563514.~~
- [x] Test if BP mods work, and fix if they don't.

**Comment by UE4SS** [comment]
The class `UDynamicClass` has been removed, and this is one of the UObjects that we demand exist before assuming that UE is initialized.
As a result, we're getting stuck in an infinite GUObjectArray loop when it tries to find `UDynamicClass`.

**Comment by UE4SS** [comment]
The property `Actor` inside `FActorInstanceHandle` was renamed to `ReferenceObject`.
This will affect any mods that use `FHitResult`.
This also affects our `LineTraceMod` as it references this `Actor` property.

There are other changes to `FActorInstanceHandle` but we don't use this struct ourselves so I don't think there's anything we need to do about this right now.

**Comment by UE4SS** [comment]
BP modding still needs to be tested.

**Comment by UE4SS** [comment]
I have confirmed that `BPModLoaderMod` is broken in 5.4.
When we call `UAssetRegistryHelpers::GetAsset`, eventually `LoadPackage` is called and in 5.4 (and presumably in 5.3) it doesn't seem to load the package.
I have not yet figured out why `LoadPackage` fails.

**Comment by UE4SS** [comment]
My mistake, it's `FindObjectFast<UObject>(FoundPackage, AssetName)` that's failing, not `LoadPackage`.
That bit of code can be found in `AssetData.h` @ L552 in the `FastGetAsset` function.

**Comment by UE4SS** [comment]
The mod loading problem appears to be caused by this change in UE:
```diff
Subject: [PATCH] Fix FastGetAsset that was looking in partially loaded packages
---
Index: Engine/Source/Runtime/CoreUObject/Public/AssetRegistry/AssetData.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Engine/Source/Runtime/CoreUObject/Public/AssetRegistry/AssetData.h b/Engine/Source/Runtime/CoreUObject/Public/AssetRegistry/AssetData.h
--- a/Engine/Source/Runtime/CoreUObject/Public/AssetRegistry/AssetData.h	(revision 88d71359b9be822ce28604bc98eff0c3e4172ab5)
+++ b/Engine/Source/Runtime/CoreUObject/Public/AssetRegistry/AssetData.h	(revision af065d5025bdf7e4e3f433302aa20bc7f9b62fc6)
@@ -510,6 +510,13 @@
 
 		// We load PackageName rather than using GetObjectPath because external assets may be saved in a different package to their loaded path. 
 		UPackage* FoundPackage = FindObjectFast<UPackage>(nullptr, PackageName);
+
+		// We could find an existing package in memory that is still pending load in the loader.
+		if (FoundPackage && !FoundPackage->IsFullyLoaded())
+		{
+			FoundPackage = nullptr;
+		}
+
 		if (FoundPackage == nullptr && bLoad)
 		{
 			FLinkerInstancingContext InstancingContext(MoveTemp(LoadTags));

```
When setting a breakpoint on it in the debugger and setting `FoundPackage` to nullptr and then forcing the next execution to be inside the `FoundPackage == nullptr` if-statement body, the call to `FindObjectFast` succeeds in finding the ModActor object.

**Comment by UE4SS** [comment]
I'm currently unsure how to fix this without abandoning the use of `UAssetRegistryHelpers::GetAsset`.

**Comment by UE4SS** [comment]
In addition to the above problem, we also have a second problem, this time with `UGameplayStatics::BeginDeferredActorSpawnFromClass`.
They added a param to it: `EnumProperty /Script/Engine.GameplayStatics:BeginDeferredActorSpawnFromClass:TransformScaleMethod`
To fix this, we must add an additional version check to our wrapper in `GameplayStatics.cpp`.

**Comment by UE4SS** [comment]
Two things:
1. I added support for `BeginDeferredActorSpawnFromClass` via https://github.com/Re-UE4SS/UEPseudo/pull/90
2. I appear to be somewhat wrong about the nature of https://github.com/UE4SS-RE/RE-UE4SS/issues/502#issuecomment-2111563514.
    While what I said there is true, when I tested it earlier, this problem is since inexplicably disappeared.
Mod loading is now working in 5.4, and is untested in 5.2 and 5.3, maybe someone can test that ?

**Comment by Buckminsterfullerene02** [comment]
> Mod loading is now working in 5.4, and is untested in 5.2 and 5.3, maybe someone can test that ?
Tested and working in a 5.3 game it was previously not working in.

**Comment by UE4SS** [comment]
> > Mod loading is now working in 5.4, and is untested in 5.2 and 5.3, maybe someone can test that ?
> 
> Tested and working in a 5.3 game it was previously not working in.

That's awesome, thanks for testing.
#503 should definitely be ready to be merged alongside the UEPseudo equivalent then.
