### ISSUE TITLE
[Docs Tracking] Docs todo

### ISSUE THREAD

**Issue by Buckminsterfullerene02** [UE4SS-RE/RE-UE4SS#513]
Will update as I think of things that need to be done.

- [ ] Explain ABI/that building mods on latest main won't necessarily work on latest release. Recommend that mod developers develop mods on commit of their release of choice
- [ ] Explain difference of xmake f -m <target> and xmake/xmake build. Some users have been confused that the former command "doesn't work" because they aren't aware it is only for setting configuration
- [ ] Fill out contributing page (and maybe include in repo root as well). This should include; how to make changelog entries, how PR and release system works, using clang format, how to update docs, etc.
- [ ] Update build instructions with -y on commands because minor QoL

**Comment by bitonality** [comment]
Adding these commands that are now available as a part of #494 but aren't being advertised publicly yet.

Install a mod to a game.
`xmake install -o "C:/MyGame/" <mod_name>`
Install all mods to a game.
`xmake install -o "C:/MyGame/" -g mods`
Currently installing mods also automatically installs the locally compiled version of UE4SS. I'm looking into a way to explicitly disable this option if you want to test mods against a released version of UE4SS...


I also added the ability to install arbitrary files alongside the mod by using
```lua
target("mymod")
    add_extrafiles("someconfig.json")
```
The xmake install command will automatically pick these files up and install them with the mod dll.

`xmake install -o "C:/MyGame/" UE4SS`
Installs dwmapi.dll, UE4SS.dll and UE4SS.pdb to the game folder.

**Comment by UE4SS** [comment]
Updated the first checklist entry, and added another related one.
I think this makes more sense, but feel free to revert or make whatever changes.

**Comment by Buckminsterfullerene02** [comment]
Added part about linking and such. Any other examples we should provide?
